"""Add password column to users

Revision ID: 8aba547a6b06
Revises: e1fcb3d6ed1a
Create Date: 2025-09-06 18:10:23.826059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8aba547a6b06'
down_revision: Union[str, Sequence[str], None] = 'e1fcb3d6ed1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'is_private')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
