"""sync models with db

Revision ID: 9ba19f380c04
Revises: 8aba547a6b06
Create Date: 2025-09-06 20:30:28.085355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ba19f380c04'
down_revision: Union[str, Sequence[str], None] = '8aba547a6b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('language', sa.String(length=50), nullable=False))
    op.drop_column('submissions', 'submitted_at')
    op.add_column('testcases', sa.Column('is_sample', sa.Boolean(), nullable=True))
    op.alter_column('testcases', 'input_data',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('testcases', 'expected_output',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testcases', 'expected_output',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('testcases', 'input_data',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_column('testcases', 'is_sample')
    op.add_column('submissions', sa.Column('submitted_at', mysql.DATETIME(), nullable=True))
    op.drop_column('submissions', 'language')
    # ### end Alembic commands ###
